eureka:
  client:
    enabled: false

server:
  port: 8765

spring:
  application:
    name: gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true

      routes:

      - id: post-service
        uri: lb://post-service
        predicates:
        - Path=/posts/**

      - id: user-service
        uri: lb://user-service
        predicates:
        - Path=/users/**