eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

logging:
  level:
    reactor:
      netty: INFO
    org:
      springframework:
        cloud:
          gateway: TRACE

server:
  port: 8765

spring:
  application:
    name: reverse-proxy

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true

      httpclient:
        wiretap: true
      httpserver:
        wiretap: true

      routes:

      - id: like-service
        uri: lb://like-service
        order: -2
        predicates:
        - Path=/posts/*/likes/**

      - id: post-service
        uri: lb://post-service
        order: -1
        predicates:
        - Path=/posts/**

      - id: user-service
        uri: lb://user-service
        predicates:
        - Path=/users/**

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods:
            - GET