eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

logging:
  level:
    reactor:
      netty: INFO
    org:
      springframework:
        cloud:
          gateway: TRACE

server:
  port: 8765

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true

      httpclient:
        wiretap: true
      httpserver:
        wiretap: true

      routes:

      - id: follow-service
        uri: lb://follow-service
        order: 1
        predicates:
        - Path=/users/*/following/**, /users/*/followers/**, /users/*/follow/**

      - id: like-service
        uri: lb://like-service
        order: -2
        predicates:
        - Path=/posts/*/likes/**

      - id: comment-service
        uri: lb://comment-service
        order: -1
        predicates:
        - Path=/posts/*/comments/**

      - id: post-service
        uri: lb://post-service
        order: 0
        predicates:
        - Path=/users/*/posts/**

      - id: user-service
        uri: lb://user-service
        order: 2
        predicates:
        - Path=/users/**

      - id: authorisation-server
        uri: ${AUTHORIZATION_SERVER_URI:http://localhost:9000}
        order: 3
        predicates:
        - Path=/.well-known/openid-configuration,/oauth2/**, /userinfo/**, /connect/**

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000}
            allowedMethods:
            - GET
            - HEAD
            - PATCH
            - OPTIONS
            - POST
            - PUT
            - DELETE
            allowedHeaders:
            - Origin
            - X-Requested-With
            - Content-Type
            - Accept