eureka:
  client:
    serviceUrl:
      defaultZone: http://naming-server:8761/eureka

server:
  port: 8765

spring:
  application:
    name: gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true

      routes:
      
      - id: posts-service
        uri: lb://posts-service
        predicates:
        - Path=/posts/**