eureka:
  client:
    serviceUrl:
      defaultZone: http://service-registry:8761/eureka

logging:
  level:
    reactor:
      netty: INFO
    org:
      springframework:
        cloud:
          gateway: TRACE

server:
  port: 8765

spring:
  application:
    name: reverse-proxy

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true

      httpclient:
        wiretap: true
      httpserver:
        wiretap: true

      routes:

      - id: authorization-server
        uri: lb://authorization-server
        predicates:
        - Path=/oauth2/**
        filters:
        - RewritePath=/oauth2/oauth/(?<segment>.*), /oauth2/$\{segment}

      - id: post-service
        uri: lb://post-service
        predicates:
        - Path=/posts/**

      - id: user-service
        uri: lb://user-service
        predicates:
        - Path=/users/**